export const NOMEN_COLUMNS = [
  { field: 'singular', headerName: 'Singular', flex: 1.2 },
  { field: 'plural', headerName: 'Plural', flex: 1.2 },
  { field: 'adjective', headerName: 'Adjektiv', flex: 1 },
  { field: 'prefix', headerName: 'Präfix', flex: 0.8 },
  { field: 'suffix', headerName: 'Suffix', flex: 0.8 },
  { field: 'gender', headerName: 'Genus', flex: 0.7 },
  { field: 'declinationRule', headerName: 'Deklinationsregel', flex: 1.1 },
  { field: 'declinationPattern', headerName: 'Muster', flex: 0.7 },
  { field: 'campaignSetting', headerName: 'Setting', flex: 0.9 },
  { field: 'tags', headerName: 'Tags', flex: 1.5 },
];

export const ADJ_COLUMNS = [
  { field: 'positive', headerName: 'Positiv', flex: 1 },
  { field: 'comparative', headerName: 'Komparativ', flex: 1 },
  { field: 'superlative', headerName: 'Superlativ', flex: 1 },
  { field: 'campaignSetting', headerName: 'Setting', flex: 1 },
  { field: 'tags', headerName: 'Tags', flex: 1.5 },
];

export const GENRE_COLUMNS = [
  { field: 'title', headerName: 'Titel (DSL)', flex: 2.5, dsl: true },
  { field: 'tags', headerName: 'Tags', flex: 2, dsl: true },
  { field: 'genre', headerName: 'Genre', flex: 1 },
];

export const DEFAULT_SCHEMAS = [
  // Genre
  {
    id: 'genre',
    label: 'Genre-Templates',
   file: './scripts/data/genre/genre.csv',
    csvFile: 'genre.csv',
    type: 'genre',
    columns: GENRE_COLUMNS,
    lemma: null,
    group: 'genre',
    deletable: true,
  },

  // Nomen
  {
    id: 'Waffe',
    label: 'Waffe',
    file: './scripts/data/nomen/Waffen.csv',
    csvFile: 'Waffen.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Waffe',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Tier',
    label: 'Tier',
    file: './scripts/data/nomen/Tiere.csv',
    csvFile: 'Tiere.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Tier',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Volk',
    label: 'Volk',
    file: './scripts/data/nomen/Voelker.csv',
    csvFile: 'Voelker.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Volk',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Klasse',
    label: 'Klasse',
    file: './scripts/data/nomen/Klassen.csv',
    csvFile: 'Klassen.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Klasse',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Kreaturtyp',
    label: 'Kreaturtyp',
    file: './scripts/data/nomen/Kreaturtypen.csv',
    csvFile: 'Kreaturtypen.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Kreaturtyp',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Beruf',
    label: 'Beruf',
    file: './scripts/data/nomen/Berufe.csv',
    csvFile: 'Berufe.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Beruf',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Rüstung',
    label: 'Rüstung',
    file: './scripts/data/nomen/Ruestungen.csv',
    csvFile: 'Ruestungen.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Rüstung',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Gebäude',
    label: 'Gebäude',
    file: './scripts/data/nomen/Gebaeude.csv',
    csvFile: 'Gebaeude.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Gebäude',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Ereignis',
    label: 'Ereignis',
    file: './scripts/data/nomen/Ereignisse.csv',
    csvFile: 'Ereignisse.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Ereignis',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Metall',
    label: 'Metall',
    file: './scripts/data/nomen/Metalle.csv',
    csvFile: 'Metalle.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Metall',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Abenteuerausrüstung',
    label: 'Abenteuerausrüstung',
    file: './scripts/data/nomen/Abenteuerausruestung.csv',
    csvFile: 'Abenteuerausruestung.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Abenteuerausrüstung',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Terrain',
    label: 'Terrain',
    file: './scripts/data/nomen/Terrain.csv',
    csvFile: 'Terrain.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Terrain',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Religioeses',
    label: 'Religiöses',
    file: './scripts/data/nomen/Religioeses.csv',
    csvFile: 'Religioeses.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Religioeses',
    group: 'nomen',
    deletable: true,
  },
  {
    id: 'Ort',
    label: 'Ort',
    file: './scripts/data/nomen/Orte.csv',
    csvFile: 'Orte.csv',
    type: 'nomen',
    columns: NOMEN_COLUMNS,
    lemma: 'Ort',
    group: 'nomen',
    deletable: true,
  },

  // Adjektive
  {
    id: 'PersonAussehen',
    label: 'PersonAussehen',
    file: './scripts/data/adjektive/PersonAussehen.csv',
    csvFile: 'PersonAussehen.csv',
    type: 'adjektiv',
    columns: ADJ_COLUMNS,
    lemma: 'PersonAussehen',
    group: 'adjektiv',
    deletable: true,
  },
  {
    id: 'Himmelsrichtung',
    label: 'Himmelsrichtung',
    file: './scripts/data/adjektive/Himmelsrichtungen.csv',
    csvFile: 'Himmelsrichtungen.csv',
    type: 'adjektiv',
    columns: ADJ_COLUMNS,
    lemma: 'Himmelsrichtung',
    group: 'adjektiv',
    deletable: true,
  },
];